### ISSUE TITLE
Docs for v2

### ISSUE THREAD

**Issue by abhinavk99** [ickerio/fortnite.js#5]
We need updated docs for v2

We should cover the new endpoints:
- match history
- current weekly challenges
- current store

**Comment by ickerio** [comment]
Do you think it would be appropriate to use JSdoc? I've used it on my other project pubg.js, so I could easily transfer the config from that project over.

**Comment by abhinavk99** [comment]
Yeah that's what I did on my other projects as well

**Comment by ickerio** [comment]
If we can start adding the doc to our code that would be great, I'll do the config. See pubg.js.org

**Comment by abhinavk99** [comment]
I just added JSDoc comments to document all the classes, public methods, and class attributes in 6bddab3. I don't think I missed anything, but it would be great if you could go through once to just make sure.

**Comment by ickerio** [comment]
Great! Found one or two errors, but corrected. I've just added the config. Use master to make changes and stuff, this will automatically run a test file (still TODO). When you push to stable it should create a new JSdoc site and automatically push it to fortnite.js.org as well as publishing to NPM (as long as the package.json version field has been updated). This makes it really easy to make changes and quickly publish when neccesary without directly interacting with NPM or GH pages. Still waiting on js.org to accept our request but this shouldn't take long :)
Thanks!

**Comment by abhinavk99** [comment]
So if I understand correctly, every time I make a change, I push to master. Merging master into stable will cause the NPM site and GH pages to update so that should only be done on release of a new version. Is that right?

**Comment by abhinavk99** [comment]
Oh yeah also, since the NPM page uses your account info, I think it would be better if you handled the releases.

**Comment by abhinavk99** [comment]
I'm closing this since https://fortnite.js.org got approved.
