### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by charis38** [ickerio/fortnite.js#6]
Need help, don't know where else to contact you, discord link is outdated.

**Comment by abhinavk99** [comment]
The only reason I can think of is that you don't have an API token from Fortnite Tracker.

**Comment by ickerio** [comment]
Hi, if this doesn't help then you can join the discord server on the new link https://discord.gg/FeFBsqN

**Comment by Ubuntuify** [comment]
Well, I have an API key just dosen't work

**Comment by abhinavk99** [comment]
Have you tried updating fortnite.js to the newest version and getting a new API key?

**Comment by Ubuntuify** [comment]
yup..

**Comment by abhinavk99** [comment]
Sorry, I'm not really sure then. Do some of the methods work or none?
